/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.orderseat.facade.response;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-11-23")
public class SeatInfoResponse implements org.apache.thrift.TBase<SeatInfoResponse, SeatInfoResponse._Fields>, java.io.Serializable, Cloneable, Comparable<SeatInfoResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SeatInfoResponse");

  private static final org.apache.thrift.protocol.TField SEAT_INFO_DTO_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("seatInfoDtoList", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField RESULT_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("resultCode", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField DESC_FIELD_DESC = new org.apache.thrift.protocol.TField("desc", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new SeatInfoResponseStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new SeatInfoResponseTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.util.List<com.orderseat.facade.dto.SeatInfoDto> seatInfoDtoList; // required
  /**
   * 
   * @see com.orderseat.facade.enums.ResultCodeEnum
   */
  public @org.apache.thrift.annotation.Nullable com.orderseat.facade.enums.ResultCodeEnum resultCode; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String desc; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SEAT_INFO_DTO_LIST((short)1, "seatInfoDtoList"),
    /**
     * 
     * @see com.orderseat.facade.enums.ResultCodeEnum
     */
    RESULT_CODE((short)2, "resultCode"),
    DESC((short)3, "desc");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SEAT_INFO_DTO_LIST
          return SEAT_INFO_DTO_LIST;
        case 2: // RESULT_CODE
          return RESULT_CODE;
        case 3: // DESC
          return DESC;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SEAT_INFO_DTO_LIST, new org.apache.thrift.meta_data.FieldMetaData("seatInfoDtoList", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.orderseat.facade.dto.SeatInfoDto.class))));
    tmpMap.put(_Fields.RESULT_CODE, new org.apache.thrift.meta_data.FieldMetaData("resultCode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, com.orderseat.facade.enums.ResultCodeEnum.class)));
    tmpMap.put(_Fields.DESC, new org.apache.thrift.meta_data.FieldMetaData("desc", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SeatInfoResponse.class, metaDataMap);
  }

  public SeatInfoResponse() {
  }

  public SeatInfoResponse(
    java.util.List<com.orderseat.facade.dto.SeatInfoDto> seatInfoDtoList,
    com.orderseat.facade.enums.ResultCodeEnum resultCode,
    java.lang.String desc)
  {
    this();
    this.seatInfoDtoList = seatInfoDtoList;
    this.resultCode = resultCode;
    this.desc = desc;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SeatInfoResponse(SeatInfoResponse other) {
    if (other.isSetSeatInfoDtoList()) {
      java.util.List<com.orderseat.facade.dto.SeatInfoDto> __this__seatInfoDtoList = new java.util.ArrayList<com.orderseat.facade.dto.SeatInfoDto>(other.seatInfoDtoList.size());
      for (com.orderseat.facade.dto.SeatInfoDto other_element : other.seatInfoDtoList) {
        __this__seatInfoDtoList.add(new com.orderseat.facade.dto.SeatInfoDto(other_element));
      }
      this.seatInfoDtoList = __this__seatInfoDtoList;
    }
    if (other.isSetResultCode()) {
      this.resultCode = other.resultCode;
    }
    if (other.isSetDesc()) {
      this.desc = other.desc;
    }
  }

  public SeatInfoResponse deepCopy() {
    return new SeatInfoResponse(this);
  }

  @Override
  public void clear() {
    this.seatInfoDtoList = null;
    this.resultCode = null;
    this.desc = null;
  }

  public int getSeatInfoDtoListSize() {
    return (this.seatInfoDtoList == null) ? 0 : this.seatInfoDtoList.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<com.orderseat.facade.dto.SeatInfoDto> getSeatInfoDtoListIterator() {
    return (this.seatInfoDtoList == null) ? null : this.seatInfoDtoList.iterator();
  }

  public void addToSeatInfoDtoList(com.orderseat.facade.dto.SeatInfoDto elem) {
    if (this.seatInfoDtoList == null) {
      this.seatInfoDtoList = new java.util.ArrayList<com.orderseat.facade.dto.SeatInfoDto>();
    }
    this.seatInfoDtoList.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<com.orderseat.facade.dto.SeatInfoDto> getSeatInfoDtoList() {
    return this.seatInfoDtoList;
  }

  public SeatInfoResponse setSeatInfoDtoList(@org.apache.thrift.annotation.Nullable java.util.List<com.orderseat.facade.dto.SeatInfoDto> seatInfoDtoList) {
    this.seatInfoDtoList = seatInfoDtoList;
    return this;
  }

  public void unsetSeatInfoDtoList() {
    this.seatInfoDtoList = null;
  }

  /** Returns true if field seatInfoDtoList is set (has been assigned a value) and false otherwise */
  public boolean isSetSeatInfoDtoList() {
    return this.seatInfoDtoList != null;
  }

  public void setSeatInfoDtoListIsSet(boolean value) {
    if (!value) {
      this.seatInfoDtoList = null;
    }
  }

  /**
   * 
   * @see com.orderseat.facade.enums.ResultCodeEnum
   */
  @org.apache.thrift.annotation.Nullable
  public com.orderseat.facade.enums.ResultCodeEnum getResultCode() {
    return this.resultCode;
  }

  /**
   * 
   * @see com.orderseat.facade.enums.ResultCodeEnum
   */
  public SeatInfoResponse setResultCode(@org.apache.thrift.annotation.Nullable com.orderseat.facade.enums.ResultCodeEnum resultCode) {
    this.resultCode = resultCode;
    return this;
  }

  public void unsetResultCode() {
    this.resultCode = null;
  }

  /** Returns true if field resultCode is set (has been assigned a value) and false otherwise */
  public boolean isSetResultCode() {
    return this.resultCode != null;
  }

  public void setResultCodeIsSet(boolean value) {
    if (!value) {
      this.resultCode = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDesc() {
    return this.desc;
  }

  public SeatInfoResponse setDesc(@org.apache.thrift.annotation.Nullable java.lang.String desc) {
    this.desc = desc;
    return this;
  }

  public void unsetDesc() {
    this.desc = null;
  }

  /** Returns true if field desc is set (has been assigned a value) and false otherwise */
  public boolean isSetDesc() {
    return this.desc != null;
  }

  public void setDescIsSet(boolean value) {
    if (!value) {
      this.desc = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case SEAT_INFO_DTO_LIST:
      if (value == null) {
        unsetSeatInfoDtoList();
      } else {
        setSeatInfoDtoList((java.util.List<com.orderseat.facade.dto.SeatInfoDto>)value);
      }
      break;

    case RESULT_CODE:
      if (value == null) {
        unsetResultCode();
      } else {
        setResultCode((com.orderseat.facade.enums.ResultCodeEnum)value);
      }
      break;

    case DESC:
      if (value == null) {
        unsetDesc();
      } else {
        setDesc((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case SEAT_INFO_DTO_LIST:
      return getSeatInfoDtoList();

    case RESULT_CODE:
      return getResultCode();

    case DESC:
      return getDesc();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case SEAT_INFO_DTO_LIST:
      return isSetSeatInfoDtoList();
    case RESULT_CODE:
      return isSetResultCode();
    case DESC:
      return isSetDesc();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof SeatInfoResponse)
      return this.equals((SeatInfoResponse)that);
    return false;
  }

  public boolean equals(SeatInfoResponse that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_seatInfoDtoList = true && this.isSetSeatInfoDtoList();
    boolean that_present_seatInfoDtoList = true && that.isSetSeatInfoDtoList();
    if (this_present_seatInfoDtoList || that_present_seatInfoDtoList) {
      if (!(this_present_seatInfoDtoList && that_present_seatInfoDtoList))
        return false;
      if (!this.seatInfoDtoList.equals(that.seatInfoDtoList))
        return false;
    }

    boolean this_present_resultCode = true && this.isSetResultCode();
    boolean that_present_resultCode = true && that.isSetResultCode();
    if (this_present_resultCode || that_present_resultCode) {
      if (!(this_present_resultCode && that_present_resultCode))
        return false;
      if (!this.resultCode.equals(that.resultCode))
        return false;
    }

    boolean this_present_desc = true && this.isSetDesc();
    boolean that_present_desc = true && that.isSetDesc();
    if (this_present_desc || that_present_desc) {
      if (!(this_present_desc && that_present_desc))
        return false;
      if (!this.desc.equals(that.desc))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetSeatInfoDtoList()) ? 131071 : 524287);
    if (isSetSeatInfoDtoList())
      hashCode = hashCode * 8191 + seatInfoDtoList.hashCode();

    hashCode = hashCode * 8191 + ((isSetResultCode()) ? 131071 : 524287);
    if (isSetResultCode())
      hashCode = hashCode * 8191 + resultCode.getValue();

    hashCode = hashCode * 8191 + ((isSetDesc()) ? 131071 : 524287);
    if (isSetDesc())
      hashCode = hashCode * 8191 + desc.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(SeatInfoResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetSeatInfoDtoList()).compareTo(other.isSetSeatInfoDtoList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSeatInfoDtoList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.seatInfoDtoList, other.seatInfoDtoList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetResultCode()).compareTo(other.isSetResultCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResultCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.resultCode, other.resultCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDesc()).compareTo(other.isSetDesc());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDesc()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.desc, other.desc);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("SeatInfoResponse(");
    boolean first = true;

    sb.append("seatInfoDtoList:");
    if (this.seatInfoDtoList == null) {
      sb.append("null");
    } else {
      sb.append(this.seatInfoDtoList);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("resultCode:");
    if (this.resultCode == null) {
      sb.append("null");
    } else {
      sb.append(this.resultCode);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("desc:");
    if (this.desc == null) {
      sb.append("null");
    } else {
      sb.append(this.desc);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SeatInfoResponseStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SeatInfoResponseStandardScheme getScheme() {
      return new SeatInfoResponseStandardScheme();
    }
  }

  private static class SeatInfoResponseStandardScheme extends org.apache.thrift.scheme.StandardScheme<SeatInfoResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SeatInfoResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SEAT_INFO_DTO_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.seatInfoDtoList = new java.util.ArrayList<com.orderseat.facade.dto.SeatInfoDto>(_list0.size);
                @org.apache.thrift.annotation.Nullable com.orderseat.facade.dto.SeatInfoDto _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new com.orderseat.facade.dto.SeatInfoDto();
                  _elem1.read(iprot);
                  struct.seatInfoDtoList.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setSeatInfoDtoListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RESULT_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.resultCode = com.orderseat.facade.enums.ResultCodeEnum.findByValue(iprot.readI32());
              struct.setResultCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DESC
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.desc = iprot.readString();
              struct.setDescIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SeatInfoResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.seatInfoDtoList != null) {
        oprot.writeFieldBegin(SEAT_INFO_DTO_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.seatInfoDtoList.size()));
          for (com.orderseat.facade.dto.SeatInfoDto _iter3 : struct.seatInfoDtoList)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.resultCode != null) {
        oprot.writeFieldBegin(RESULT_CODE_FIELD_DESC);
        oprot.writeI32(struct.resultCode.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.desc != null) {
        oprot.writeFieldBegin(DESC_FIELD_DESC);
        oprot.writeString(struct.desc);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SeatInfoResponseTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SeatInfoResponseTupleScheme getScheme() {
      return new SeatInfoResponseTupleScheme();
    }
  }

  private static class SeatInfoResponseTupleScheme extends org.apache.thrift.scheme.TupleScheme<SeatInfoResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SeatInfoResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetSeatInfoDtoList()) {
        optionals.set(0);
      }
      if (struct.isSetResultCode()) {
        optionals.set(1);
      }
      if (struct.isSetDesc()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetSeatInfoDtoList()) {
        {
          oprot.writeI32(struct.seatInfoDtoList.size());
          for (com.orderseat.facade.dto.SeatInfoDto _iter4 : struct.seatInfoDtoList)
          {
            _iter4.write(oprot);
          }
        }
      }
      if (struct.isSetResultCode()) {
        oprot.writeI32(struct.resultCode.getValue());
      }
      if (struct.isSetDesc()) {
        oprot.writeString(struct.desc);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SeatInfoResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.seatInfoDtoList = new java.util.ArrayList<com.orderseat.facade.dto.SeatInfoDto>(_list5.size);
          @org.apache.thrift.annotation.Nullable com.orderseat.facade.dto.SeatInfoDto _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new com.orderseat.facade.dto.SeatInfoDto();
            _elem6.read(iprot);
            struct.seatInfoDtoList.add(_elem6);
          }
        }
        struct.setSeatInfoDtoListIsSet(true);
      }
      if (incoming.get(1)) {
        struct.resultCode = com.orderseat.facade.enums.ResultCodeEnum.findByValue(iprot.readI32());
        struct.setResultCodeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.desc = iprot.readString();
        struct.setDescIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

